export default function TermsPage() {
  return (
    <main className="page-main" style={{ maxWidth: "680px" }}>
      <div style={{ marginBottom: "2.5rem" }}>
        <p className="eyebrow">Legal</p>
        <h1 className="heading" style={{ fontSize: "36px" }}>Terms of Service</h1>
        <p style={{ color: "#888", fontSize: "12px", marginTop: "0.5rem" }}>Last updated: April 2026</p>
      </div>

      <div style={{ color: "#333", fontSize: "14px", lineHeight: "1.8" }} className="space-y-6">
        <section>
          <h2 className="heading" style={{ fontSize: "16px", marginBottom: "0.5rem" }}>The service</h2>
          <p>IB Core OS is a study tool for International Baccalaureate Diploma students. It provides AI-assisted guidance for Theory of Knowledge, CAS, and Extended Essay components. It is not affiliated with or endorsed by the International Baccalaureate Organisation.</p>
        </section>

        <div className="divider" />

        <section>
          <h2 className="heading" style={{ fontSize: "16px", marginBottom: "0.5rem" }}>Your account</h2>
          <p>You must be at least 13 years old to use this service. You are responsible for keeping your login credentials secure. One account per person — do not share accounts.</p>
        </section>

        <div className="divider" />

        <section>
          <h2 className="heading" style={{ fontSize: "16px", marginBottom: "0.5rem" }}>Acceptable use</h2>
          <p>Use IB Core OS to support your own learning. Do not:</p>
          <ul style={{ paddingLeft: "1.25rem", margin: "0.5rem 0 0" }}>
            <li>Submit AI-generated text as your own IB work without disclosure (academic honesty applies)</li>
            <li>Attempt to reverse-engineer or scrape the service</li>
            <li>Share your account with others</li>
            <li>Use the service for anything illegal</li>
          </ul>
        </section>

        <div className="divider" />

        <section>
          <h2 className="heading" style={{ fontSize: "16px", marginBottom: "0.5rem" }}>Payments & refunds</h2>
          <p>Subscriptions are billed monthly. Payments are processed by <strong>Paddle</strong>, who acts as Merchant of Record — Paddle's terms and privacy policy also apply to your purchase. You can cancel at any time from your profile — cancellation takes effect at the end of the current billing period. We offer a refund within 7 days of initial purchase if you are not satisfied. Contact <a href="mailto:hello@ibcoreos.com" style={{ color: "var(--fg)" }}>hello@ibcoreos.com</a>.</p>
        </section>

        <div className="divider" />

        <section>
          <h2 className="heading" style={{ fontSize: "16px", marginBottom: "0.5rem" }}>AI-generated content</h2>
          <p>Feedback and suggestions from IB Core OS are generated by AI and may contain errors. Do not treat them as authoritative IB guidance. Always verify with your teacher or coordinator.</p>
        </section>

        <div className="divider" />

        <section>
          <h2 className="heading" style={{ fontSize: "16px", marginBottom: "0.5rem" }}>Liability</h2>
          <p>IB Core OS is provided as-is. We are not liable for IB assessment outcomes, data loss due to circumstances outside our control, or indirect damages. Our liability is limited to the amount you paid us in the past 12 months.</p>
        </section>

        <div className="divider" />

        <section>
          <h2 className="heading" style={{ fontSize: "16px", marginBottom: "0.5rem" }}>Changes</h2>
          <p>We may update these terms. We will notify you by email if changes are material. Continued use after the effective date constitutes acceptance.</p>
        </section>

        <div className="divider" />

        <section>
          <h2 className="heading" style={{ fontSize: "16px", marginBottom: "0.5rem" }}>Contact</h2>
          <p><a href="mailto:hello@ibcoreos.com" style={{ color: "var(--fg)" }}>hello@ibcoreos.com</a></p>
        </section>
      </div>
    </main>
  );
}
