export const TOK_PROMPTS: Record<number, string> = {
  1:  "What counts as knowledge?",
  2:  "Are some types of knowledge less open to interpretation than others?",
  3:  "What is the relationship between personal experience and the acquisition of knowledge?",
  4:  "Does gaining knowledge always benefit the individual or society?",
  5:  "Do we need other people in order to understand ourselves?",
  6:  "Can we have knowledge of the future?",
  7:  "Is it possible to understand how different groups of people interpret the world?",
  8:  "Is knowledge limited by language?",
  9:  "Can intuition be a reliable way of knowing?",
  10: "To what extent do we construct knowledge rather than discover it?",
  11: "Can new knowledge change established values or beliefs?",
  12: "Is certainty possible?",
  13: "How important is the quality of evidence in the pursuit of knowledge?",
  14: "Is there knowledge that should not be sought?",
  15: "Is it possible to know something that cannot be expressed in language?",
  16: "What is the relationship between knowledge and culture?",
  17: "How do we know whether the knowledge we produce is valuable?",
  18: "Can we distinguish fact from opinion?",
  19: "Is it possible to have knowledge without experience?",
  20: "What is the relationship between imagination and knowledge?",
  21: "How does the way we categorise things affect what we know?",
  22: "Should those seeking knowledge be free from all constraints?",
  23: "Is all knowledge created equal?",
  24: "How do we know when to stop seeking knowledge?",
  25: "Is knowledge shared or individual?",
  26: "Can we separate knowledge from the knower?",
  27: "What is the relationship between knowledge and power?",
  28: "Can scientific knowledge coexist with religious belief?",
  29: "How do we judge what is and what is not artistic?",
  30: "Is there a moral obligation to share knowledge?",
  31: "Can historical knowledge change over time?",
  32: "Is mathematical knowledge discovered or invented?",
  33: "What is the relationship between technology and knowledge?",
  34: "Can emotion be a reliable source of knowledge?",
  35: "Is the pursuit of knowledge always a good thing?",
};
