"use client";

import { useState, useEffect, useCallback, useRef } from "react";
import { createPortal } from "react-dom";
import { useToast } from "@/lib/toast";

interface Props {
  exhibitionId: string;
}

export default function ExportButton({ exhibitionId }: Props) {
  const [open, setOpen] = useState(false);
  const [visible, setVisible] = useState(false);
  const [exiting, setExiting] = useState(false);
  const [content, setContent] = useState("");
  const [loading, setLoading] = useState(false);
  const [mode, setMode] = useState<"preview" | "txt" | "md">("preview");
  const { showToast } = useToast();
  const timerRef = useRef<ReturnType<typeof setTimeout>>(null);
  const rafRef = useRef<number>(0);

  const url = `/api/tok/export-text?id=${exhibitionId}`;

  const fetchContent = useCallback(async () => {
    setLoading(true);
    try {
      const res = await fetch(url);
      if (!res.ok) { const err = await res.json().catch(() => ({ error: "Load failed" })); showToast(err.error ?? "Load failed", "error"); close(); return; }
      setContent(await res.text());
    } catch { showToast("Load failed", "error"); close(); }
    finally { setLoading(false); }
  }, [url, showToast]);

  useEffect(() => {
    if (visible) {
      const t = setTimeout(fetchContent, 200);
      return () => clearTimeout(t);
    }
  }, [visible, fetchContent]);

  useEffect(() => {
    if (visible && !exiting) document.body.style.overflow = "hidden";
    else document.body.style.overflow = "";
    return () => { document.body.style.overflow = ""; };
  }, [visible, exiting]);

  useEffect(() => {
    function handleKey(e: KeyboardEvent) {
      if (e.key === "Escape" && visible) close();
    }
    if (visible) window.addEventListener("keydown", handleKey);
    return () => window.removeEventListener("keydown", handleKey);
  }, [visible]);

  function openModal() {
    setOpen(true);
    rafRef.current = requestAnimationFrame(() => {
      rafRef.current = requestAnimationFrame(() => {
        setVisible(true);
      });
    });
  }

  function close() {
    setExiting(true);
    setVisible(false);
    timerRef.current = setTimeout(() => {
      setOpen(false);
      setExiting(false);
    }, 180);
  }

  useEffect(() => {
    return () => {
      if (timerRef.current) clearTimeout(timerRef.current);
      cancelAnimationFrame(rafRef.current);
    };
  }, []);

  function mdFromText(text: string): string {
    const lines = text.split("\n");
    const md: string[] = [];
    for (const line of lines) {
      const t = line.trim();
      if (t.startsWith("TOK EXHIBITION")) { md.push("# TOK Exhibition"); continue; }
      if (t.startsWith("=")) continue;
      if (t.startsWith("-".repeat(20))) continue;
      if (t.startsWith("Title:")) { md.push(`**${t}**`); continue; }
      if (t.startsWith("Prompt ")) { md.push(`*${t}*`); continue; }
      if (t.startsWith("Exported:")) { md.push(`*${t}*`); continue; }
      if (t.startsWith("Prompt description:")) { md.push(`\n${t}`); continue; }
      if (t.endsWith("Object") && !t.includes(":") && !t.startsWith(" ")) { md.push(`\n---\n\n### ${t}`); continue; }
      if (t.startsWith("Object:")) { md.push(`\n**${t}**`); continue; }
      if (t.startsWith("Type:")) { md.push(`\n*${t}*`); continue; }
      if (t.startsWith("Description:")) { md.push(`\n${t}`); continue; }
      if (t.startsWith("Justification:")) { md.push(`\n### Justification\n`); continue; }
      if (t.startsWith("(no justification")) { md.push(`> ${t}`); continue; }
      if (t.startsWith("Total justification")) { md.push(`\n---\n\n**${t}**`); continue; }
      if (t.startsWith("Generated by")) { md.push(`\n---\n*${t}*`); continue; }
      if (t.startsWith("IB academic")) { md.push(`*${t}*`); continue; }
      if (t) md.push(t);
    }
    return md.join("\n");
  }

  function downloadFile(text: string, filename: string, mime: string) {
    const blob = new Blob([text], { type: `${mime};charset=utf-8` });
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = filename;
    a.click();
    URL.revokeObjectURL(a.href);
  }

  function handlePrint() {
    close();
    setTimeout(() => window.print(), 200);
  }

  const shouldRender = open || exiting;

  return (
    <>
      <button
        onClick={openModal}
        className="btn-ghost btn-ghost-hover"
        style={{ fontSize: "11px", padding: "4px 10px" }}
      >
        Export
      </button>

      {shouldRender && typeof document !== "undefined" && createPortal(
        <div
          style={{
            position: "fixed",
            inset: 0,
            zIndex: 99999,
            background: visible ? "rgba(26,26,26,0.45)" : "rgba(26,26,26,0)",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            padding: "1rem",
            transition: "background 0.18s ease",
          }}
          onClick={(e) => { if (e.target === e.currentTarget) close(); }}
        >
          <div
            style={{
              background: "var(--surface)",
              border: "2px solid var(--fg)",
              borderRadius: "var(--radius)",
              width: "100%",
              maxWidth: "680px",
              maxHeight: "min(92vh, 800px)",
              display: "flex",
              flexDirection: "column",
              opacity: visible ? 1 : 0,
              transform: visible ? "translateY(0)" : "translateY(-6px)",
              transition: "opacity 0.18s ease, transform 0.18s ease",
            }}
          >
            <div style={{
              display: "flex", alignItems: "center", justifyContent: "space-between",
              padding: "1rem 1.25rem", borderBottom: "2px solid var(--border)",
            }}>
              <span className="eyebrow" style={{ fontSize: "13px" }}>Export Exhibition</span>
              <button
                onClick={close}
                style={{
                  background: "none", border: "none", cursor: "pointer",
                  fontSize: "16px", fontWeight: 700, padding: "2px 6px", lineHeight: 1,
                }}
              >
                ✕
              </button>
            </div>

            <div style={{
              display: "flex", gap: "4px",
              padding: "0.75rem 1.25rem", borderBottom: "1px solid #f0ebe0",
            }}>
              {(["preview", "txt", "md"] as const).map((fmt) => (
                <button
                  key={fmt}
                  onClick={() => setMode(fmt)}
                  style={{
                    background: mode === fmt ? "var(--fg)" : "transparent",
                    color: mode === fmt ? "var(--bg)" : "var(--fg)",
                    border: "2px solid var(--fg)", borderRadius: "4px",
                    padding: "4px 12px", fontSize: "11px", fontWeight: 700,
                    textTransform: "uppercase", letterSpacing: "0.06em",
                    cursor: "pointer", transition: "background 0.1s",
                  }}
                >
                  {fmt === "preview" ? "Preview" : fmt.toUpperCase()}
                </button>
              ))}
            </div>

            <div style={{
              flex: 1, overflow: "auto",
              padding: "1rem 1.25rem",
              minHeight: "280px",
              maxHeight: "55vh",
            }}>
              {!loading && content && (
                <pre style={{
                  margin: 0, fontFamily: "monospace", fontSize: "12px",
                  lineHeight: 1.6, whiteSpace: "pre-wrap", wordBreak: "break-word",
                  color: "var(--fg)",
                }}>
                  {mode === "preview"
                    ? (content.split("\n").slice(0, 40).join("\n") + (content.split("\n").length > 40 ? "\n\n..." : ""))
                    : (mode === "md" ? mdFromText(content) : content)}
                </pre>
              )}
            </div>

            <div style={{
              display: "flex", gap: "8px",
              padding: "0.75rem 1.25rem", borderTop: "2px solid var(--border)",
              flexWrap: "wrap",
            }}>
              <button
                onClick={() => downloadFile(content, `tok-exhibition-${exhibitionId.slice(0, 8)}.txt`, "text/plain")}
                className="btn-primary btn-primary-hover"
                style={{ flex: "1 1 140px", fontSize: "11px", padding: "6px 12px" }}
              >
                Download TXT
              </button>
              <button
                onClick={() => { const md = mdFromText(content); downloadFile(md, `tok-exhibition-${exhibitionId.slice(0, 8)}.md`, "text/markdown"); }}
                className="btn-primary btn-primary-hover"
                style={{ flex: "1 1 140px", fontSize: "11px", padding: "6px 12px" }}
              >
                Download MD
              </button>
              <button onClick={handlePrint} className="btn-ghost btn-ghost-hover" style={{ flex: "1 1 140px", fontSize: "11px", padding: "6px 12px" }}>
                Print PDF
              </button>
            </div>
          </div>
        </div>,
        document.body
      )}
    </>
  );
}
