import { createClient } from "@/lib/supabase-server";
import { NextRequest, NextResponse } from "next/server";
import { TOK_PROMPTS } from "@/lib/tok-prompts";

export async function GET(request: NextRequest) {
  const id = request.nextUrl.searchParams.get("id");
  if (!id) return NextResponse.json({ error: "Missing id" }, { status: 400 });

  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const { data: exhibition } = await supabase
    .from("tok_exhibitions")
    .select("*")
    .eq("id", id)
    .eq("user_id", user.id)
    .single();

  if (!exhibition) return NextResponse.json({ error: "Not found" }, { status: 404 });

  const { data: objects } = await supabase
    .from("tok_objects")
    .select("*")
    .eq("exhibition_id", id)
    .order("position", { ascending: true });

  const prompt = TOK_PROMPTS[exhibition.prompt_id];
  const ordinals = ["First", "Second", "Third"];

  const lines: string[] = [
    "TOK EXHIBITION",
    "=".repeat(60),
    "",
    `Title: ${exhibition.title}`,
    `Prompt ${exhibition.prompt_id}: ${prompt?.title ?? `Prompt ${exhibition.prompt_id}`}`,
    `Exported: ${new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" })}`,
    "",
    prompt?.description ? `Prompt description:\n${prompt.description}` : "",
    "",
    "=".repeat(60),
    "",
  ];

  (objects ?? []).forEach((obj: Record<string, unknown>, i: number) => {
    lines.push(`${ordinals[i] ?? `Object ${i + 1}`} Object`);
    lines.push("-".repeat(40));
    lines.push(`Object: ${obj.title}`);
    if (obj.object_type) lines.push(`Type: ${obj.object_type}`);
    if (obj.description) lines.push(`\nDescription:\n${obj.description}`);
    lines.push("");
    lines.push("Justification:");
    lines.push(obj.justification ? String(obj.justification) : "(no justification written yet)");
    lines.push("");
    lines.push("=".repeat(60));
    lines.push("");
  });

  const wordCount = (objects ?? []).reduce((sum: number, o: Record<string, unknown>) => {
    const j = typeof o.justification === "string" ? o.justification.trim() : "";
    return sum + (j ? j.split(/\s+/).length : 0);
  }, 0);

  lines.push(`Total justification word count: ${wordCount}`);
  lines.push("");
  lines.push("---");
  lines.push("Generated by Corespace (corespace.app) — for study purposes only.");
  lines.push("IB academic honesty policy applies. Disclose AI assistance to your supervisor.");

  const text = lines.filter((l) => l !== undefined).join("\n");

  return new NextResponse(text, {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Content-Disposition": `attachment; filename="tok-exhibition-${id.slice(0, 8)}.txt"`,
    },
  });
}
